spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/study
    username: study
    password: study
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
