spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/study
    username: study
    password: study
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  # chaos monkey 활성화
  profiles:
    active: chaos-monkey

management:
  endpoint:
    chaosmonkey:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,chaosmonkey

# Repository Watcher 활성화
chaos:
  monkey:
    watcher:
      repository: true